# Generated by Django 6.0.5 on 2026-05-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Начальный депозит",
                    ),
                ),
                (
                    "target_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цель"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Фото профиля",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата сделки")),
                ("symbol", models.CharField(max_length=20, verbose_name="Инструмент")),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Покупка"), ("SELL", "Продажа")],
                        max_length=10,
                        verbose_name="Тип сделки",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Прибыль / Убыток ($)",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="trades/",
                        verbose_name="Скриншот сделки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
