# Generated by Django 6.0.5 on 2026-05-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trade",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="trade",
            name="profit",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Результат ($)"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="screenshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="trades/", verbose_name="Скриншот"
            ),
        ),
    ]
