# Generated by Django 6.0.5 on 2026-05-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_trade_options_alter_trade_profit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trade",
            options={},
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="symbol",
            field=models.CharField(
                choices=[
                    ("XAUUSD", "Золото (XAUUSD)"),
                    ("XAGUSD", "Серебро (XAGUSD)"),
                    ("BTCUSD", "Bitcoin (BTCUSD)"),
                    ("ETHUSD", "Ethereum (ETHUSD)"),
                    ("EURUSD", "EUR/USD"),
                    ("GBPUSD", "GBP/USD"),
                    ("NAS100", "NASDAQ 100"),
                    ("US30", "Dow Jones"),
                    ("SPX500", "S&P 500"),
                ],
                max_length=30,
                verbose_name="Актив",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[("BUY", "BUY"), ("SELL", "SELL")],
                max_length=10,
                verbose_name="Тип сделки",
            ),
        ),
    ]
