# Generated by Django 6.0.5 on 2026-05-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_alter_trade_options_alter_trade_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trade",
            options={
                "ordering": ["-date", "-id"],
                "verbose_name": "Сделка",
                "verbose_name_plural": "Сделки",
            },
        ),
        migrations.AddField(
            model_name="trade",
            name="entry_price",
            field=models.DecimalField(
                decimal_places=5, default=0, max_digits=12, verbose_name="Вход"
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="exit_price",
            field=models.DecimalField(
                decimal_places=5, default=0, max_digits=12, verbose_name="Выход"
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="lot_size",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Лот"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(verbose_name="Дата сделки"),
        ),
        migrations.AlterField(
            model_name="trade",
            name="profit",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Прибыль / Убыток"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="symbol",
            field=models.CharField(
                choices=[
                    ("XAUUSD", "Gold (XAUUSD)"),
                    ("XAGUSD", "Silver (XAGUSD)"),
                    ("BTCUSD", "Bitcoin (BTCUSD)"),
                    ("ETHUSD", "Ethereum (ETHUSD)"),
                    ("EURUSD", "EUR/USD"),
                    ("GBPUSD", "GBP/USD"),
                    ("NAS100", "NASDAQ 100"),
                    ("US30", "Dow Jones"),
                    ("SPX500", "S&P 500"),
                ],
                max_length=30,
                verbose_name="Актив",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[("BUY", "BUY"), ("SELL", "SELL")],
                max_length=10,
                verbose_name="Тип",
            ),
        ),
    ]
