# Generated by Django 6.0.5 on 2026-06-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_setup_completed",
            field=models.BooleanField(default=False),
        ),
    ]
