# Generated by Django 6.0.5 on 2026-06-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0008_todotask"),
    ]

    operations = [
        migrations.AddField(
            model_name="todotask",
            name="category",
            field=models.CharField(
                choices=[
                    ("TRADING", "Трейдинг"),
                    ("STUDY", "Обучение"),
                    ("SPORT", "Спорт"),
                    ("PERSONAL", "Личное"),
                ],
                default="TRADING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="todotask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="todotask",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
